language: ruby
sudo: false
cache: bundler

services:
  - postgresql

rvm:
  - 2.0
  - 2.1
  - 2.2

addons:
  firefox: 45.8.0esr

bundler_args: --without development --jobs=3 --retry=3

before_script:
  - psql -c "CREATE EXTENSION postgis;" -U postgres
  - psql -c "CREATE DATABASE tracks_test;" -U postgres
  - psql -c "CREATE USER tracks WITH PASSWORD 'trackspas5';" -U postgres
  - psql -c "ALTER DATABASE tracks_test OWNER TO tracks;" -U postgres
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - bundle exec rake ci:full

notifications:
  email: false
