language: ruby
sudo: false
cache: bundler

services:
  - postgresql

rvm:
  - 2.0
  - 2.1
  - 2.2

addons:
  firefox: 45.8.0esr
  chrome: stable
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
    - postgresql-10-postgis-2.4
    - postgresql-10-postgis-2.4-scripts

install: # Install ChromeDriver (64bits)
  - wget -N http://chromedriver.storage.googleapis.com/2.30/chromedriver_linux64.zip -P ~/
  - unzip ~/chromedriver_linux64.zip -d ~/
  - rm ~/chromedriver_linux64.zip
  - sudo mv -f ~/chromedriver /usr/local/share/
  - sudo chmod +x /usr/local/share/chromedriver
  - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver

env:
  global:
  - JS_DRIVER="headless_chrome"
  - PGPORT=5433
  - TRACKS_APP_USER=travis

bundler_args: --without development --jobs=3 --retry=3

before_script:
  - psql -c "CREATE EXTENSION postgis;" -U travis
  - psql -c "CREATE DATABASE tracks_test;" -U travis
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - bundle exec rake ci:full

notifications:
  email: false
