language: ruby
sudo: false
cache: bundler

services:
  - postgresql

rvm:
  - 2.5.3

addons:
  firefox: 45.8.0esr
  chrome: stable
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
    - postgresql-10-postgis-2.4
    - postgresql-10-postgis-2.4-scripts
    - chromium-chromedriver

env:
  global:
  - JS_DRIVER="headless_chrome"
  - PGPORT=5433
  - TRACKS_APP_USER=travis

bundler_args: --without development --jobs=3 --retry=3

before_script:
  - sudo ln -s /usr/lib/chromium-browser/chromedriver /usr/bin/chromedriver
  - psql -c "CREATE EXTENSION postgis;" -U travis
  - psql -c "CREATE DATABASE tracks_test;" -U travis
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - bundle exec rake ci:full

notifications:
  email: false
